---
- name: ensure docker dependencies are installed
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - apt-transport-https
    - ca-certificates

- name: ensure Docker GPG key is present
  apt_key:
    id: "{{ docker_gpg_key }}"
    keyserver: "{{ key_server }}"

- name: ensure docker repo is present
  apt_repository:
    repo: deb https://apt.dockerproject.org/repo debian-jessie main
    state: present
    filename: docker
    update_cache: true

- name: ensure docker is installed
  apt:
    name: docker-engine
    state: present
    update_cache: true
    cache_valid_time: 3600
